# Write a function to compute 5/0 and use try/except to catch the exceptions.

In [3]:
try:
    print (5/0)

except ZeroDivisionError:
    print ("You can't divide by zero!")
    

You can't divide by zero!


# 2.Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [12]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
n=0
for i in subjects:
    
    for j in verbs :
        
        for k in objects :
            
            print(i+" "+j+" "+k)
            
            

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# 1.Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, whenincreasing is False, the i-th output column is the input vector raised element-wise to the powerof N - i - 1.

In [9]:
import numpy as np

def vandermode(ivector,n,increasing = False) :

 #iterate over each number in input vector for n times. Where n is the no of column in the output matrix.

 #Use two separate condtions based on which order output matrix is needed.
    
 #Finally reshape the matrix using size of input matrix (rows) and n (no of cols) to create output
    
    if not increasing :
        omatrix = np.array([x**(n-i-1) for x in ivector for i in range (n)]).reshape(ivector.size,n)
        
    elif increasing :
        
        omatrix = np.array([x**(i) for x in ivector for i in range (n)]).reshape(ivector.size,n)
        
    return omatrix

inputvector = np.array([1,2,3,4,5])

no_col_omatrix = 4

omatrix_desc_order = vandermode (inputvector,no_col_omatrix,False)

omatrix_asc_order = vandermode (inputvector,no_col_omatrix,True)

print("The input matrix is :" ,inputvector ,"\n")

print("The no of column in output  matrix is :" ,no_col_omatrix,"\n")

print("The output matrix in descending order is :\n\n" ,omatrix_desc_order,"\n" )

print("The output matrix in ascending order is :\n\n" ,omatrix_asc_order,"\n" )


The input matrix is : [1 2 3 4 5] 

The no of column in output  matrix is : 4 

The output matrix in descending order is :

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]] 

The output matrix in ascending order is :

 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]] 

